# ARRAY PRACTICE

In [4]:
import array as arr

In [17]:
array1= [11,23,45,67,89,90]
a= arr.array('i',[11,23,45,67,89,90])
print("the new array is ",end=" ")
for i in range(0,6):
    print( a[i] ,end=" ")
print()

the new array is  11 23 45 67 89 90 


In [18]:
a.insert(4,77)
print("the new array is ",end=" ")
for i in (a):
    print(i,end=" ")
print()

the new array is  11 23 45 67 77 89 90 


In [19]:
for i in (a):
    if i==77:
        print("the array contain peak value and this is peak value ",i)
        break;
    else :
        print("Did not contain that value ")

Did not contain that value 
Did not contain that value 
Did not contain that value 
Did not contain that value 
the array contain peak value and this is peak value  77


In [47]:

def peakvalue(a,n):
  
    if (n==1):
        return 0
    if (a[0] >=a[1]):
        return 0
    if (a[n-1] >= a[n-2]):
        return n-1
    for i in range(1,n-1):
        if (a[i]>=a[i-1] and a[i] >= a[i+1]):
            return i
a = [ 1, 3, 20, 4, 1, 0 ]
n=len(a)
print("the peak index value is ",peakvalue(a,n))


the peak index value is  2


In [48]:
print("The peak value is ",a[2])

The peak value is  20


In [2]:
#ADDING TWO ARRAYS 
import numpy as np

In [8]:
a = arr.array('i',[1,2,3,4,5])
print(a)
b = arr.array('i',[6,7,8,9,1])
print(b)
for i in (a,6):
    print(a+b)


array('i', [1, 2, 3, 4, 5])
array('i', [6, 7, 8, 9, 1])
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 1])
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 1])


In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [16]:
a= arr.array('i',[7,8,9])
print("The value of array a is :",a)
b= arr.array('i',[4,2,6])
print("The value of array b is ",b)
c= arr.array('i',[])
for i in range(len(a)):
    print(a[i] + b[i])
    c.append(a[i]+ b[i])
print(c)

The value of array a is : array('i', [7, 8, 9])
The value of array b is  array('i', [4, 2, 6])
11
10
15
array('i', [11, 10, 15])


In [28]:
n= arr.array('i',[34,56,83])
f= arr.array('i',[27,56,35])
c= arr.array('i',[])
print("The value of n ",n)
print("The value of f ",f)
length_n = len(n)
length_f = len(f)
if (length_n ==length_f):
    #ONE ARRAY IS ADDED IN SECOND ARRAYS
    print(n+f)
    for i in range(len(a)):
    #SUM OF ALL ELEMENT OF ARRAY A TO ARRAY B 
        c.append(n[i]+f[i])
    print(c)
        
else :
    print("The array are not equal")

The value of n  array('i', [34, 56, 83])
The value of f  array('i', [27, 56, 35])
array('i', [34, 56, 83, 27, 56, 35])
array('i', [61, 112, 118])


In [38]:
# TWO DIMENTIONAL ARRAY 
x = np.array([[1,5,7],[3,7,1]])
y = np.array([[5,7,8],[2,4,9]])
print("The array x is \n",y)
print("The array y is \n",x)
print("The new array is ")
h = np.add(y,x)
print(h)

The array x is 
 [[5 7 8]
 [2 4 9]]
The array y is 
 [[1 5 7]
 [3 7 1]]
The new array is 
[[ 6 12 15]
 [ 5 11 10]]


In [6]:
r= np.array([[4,6,8],[2,3,6]])
d = np.array([[3,5,7],[2,6,9]])

print("The array G is : ",r)
print("The array D is :",d)
f = np.array([[],[]])
e = np.add(r,d)


The array G is :  [[4 6 8]
 [2 3 6]]
The array D is : [[3 5 7]
 [2 6 9]]


In [1]:
# TO PRINT THE REQURED INPUT BY USING LAMBDA FUNCTION
lists= [12,65,54,39,102,339,221,50,70]
result = list(filter(lambda x : (x%13 == 0),lists))
print(result)

[65, 39, 221]


In [2]:
# IF TWO ELEMENT IN TWO ARRAY IS SAME THEN USE FOLLOWING PROGRAM
def interSection(arr1,arr2):
    result = list(filter(lambda x: x in arr1, arr2))
    print("interSection : ",result)


In [5]:
if __name__ == "__main__":
    arr1 = [1,3,4,5,7]
    arr2 = [2,3,5,6]
    interSection(arr1,arr2)

interSection :  [3, 5]


### ARRAY MAIN PROGRAM

In [3]:
def binarysearch(array,i,j,x):
    ##small prblem 
    #single element search
    if i==j:
        if array[i]== x:
            return i
        else :
            return -1
    else:
        
        #big problem 
        mid = i+(j+i)//2
        if array[mid]==x:
            return mid
        
        # RESURSIVE CALL
        
        elif array[mid]<x:
            return binarysearch(array,mid+1,j,x)
        else:
            return binarysearch(array,i,mid-1,x)
array = [10,20,30,40,50,78]
i=0
j=len(array)-1
x=int(input("enter the value "))
result = binarysearch(array,i,j,x)
print("searching value is peresent at index ",result)

    

enter the value 30
searching value is peresent at index  2


In [9]:
def iterative_method(array,x):
    for i in array:
        if array[i] == x:
            # if we want the value then write i in place of TRUE
            return True
        return False
    
array = [1,2,3,4,7]
x= int(input("Enter the value to check "))
print("element is present ",iterative_method(array,x))

Enter the value to check 2
element is present  True


## SEARCH 2D MATRIX

In [5]:
def search2Dmatrix(matrix, target):
    # FOR ROW WE ARE TAKING i
    i= 0
    # FOR COLUNM WE WILL TAKE j
    j= len(matrix[0]) -1
    x= len(matrix)
    while (i <x and j>=0):
        if matrix[i][j] == target:
            print("The number is present in matrix ")
            # FOR FINDING THE INDEX TAKE i and j 
            
            return i,j
        elif (matrix[i][j] > target):
            j -= 1
        else:
            i +=1
    return -1
matrix = [[1,2,3,4],[5,6,7,8],[11,12,13,15],[17,18,20,22]]
target = int(input("Enter the number "))
result = search2Dmatrix(matrix,target)
print("result is",result)

    

Enter the number 8
The number is present in matrix 
result is (1, 3)


##SELECTION SORT

In [1]:
# CREATING THE CODE FOR SOTING THE ARRAY
def selection_sort(array):
    for i in range(len(array)):
        # min_index take the index of minimum value in a array atbeach iteration
        min_index = i
        for j in range(i+1,len(array)):
            if array[min_index]> array[j]:
                min_index = j
                # SWAP ARRAY[i] WITH ARRAY[min_index]
        array[i],array[min_index] = array[min_index],array[i]
    return array
# Driver code
array = [26,45,89,36,47,28,11]
result= selection_sort(array)
print("the result is ",result)

the result is  [11, 26, 28, 36, 45, 47, 89]


### BUBBLE SORT

In [2]:
def bubble_sort(array):
    n = len(array)
    for i in range(n-1):
        # LAST i ELEMENT ARE ALREADY IN SORTED MANNER
        for j in range(n-i-1):
            if array[j] > array[j+1]:
                #swap the element of array[j ] with array[j+1]
                array[j],array[j+1] = array[j+1],array[j]
    return array
array = [25,67,35,46,45,1]
result = bubble_sort(array)
print("The sorted array is ",result)

The sorted array is  [1, 25, 35, 45, 46, 67]


### INSERTION SORT

In [1]:
def insertionsort(array):
    for i in range(1,len(array)):
        value = array[i]
        j= i-1
        
        # MAIN CONDITION IN INSERTION SORT
        
        while j>=0 and value < array[j]:
            array[j+1] = array[j]
            j -=1
        array[j+1] = value
    return array
array = [29,45,67,38,46,78]
result = insertionsort(array)
print("the sorted array is ",result)

the sorted array is  [29, 38, 45, 46, 67, 78]


### find the missing number

In [1]:
#test case 1 --> [1,0,2,4,8,6,]
#                 |
#                  --->expected output = 3

#test case 2 --> [1,0]
#                 |
#                  --->expected output = 2(bcoz there is no element therefore 2)

#test case 3 --> [1,0,3]
#                 |
#                  --->expected output = 2




### FACEBOOK QUESTION (dividend and divisor is given find Quotient )

In [11]:
# BRUTE FORCE APPROACH
def dividenumber():
    dividend = int(input("Enter the value of dividend =  "))
    divisor = int(input("Enter the value of divisor =  "))
    output = 0
    
    # jo parant te moth asel to parnt chalnar
    
    while dividend >= divisor:
        dividend -= divisor
        
        # output madhe add honar jo parant loop chalel
        
        output +=1
    return output

# function la call kel 

df = dividenumber()
print("The Quotient is " ,df)
        
    

Enter the value of dividend =  144
Enter the value of divisor =  12
The Quotient is  12


### FIND UNIQUE EMAIL

In [5]:
def numuniqueemail(email):
    unique_email = set()
    for i in email:
        local_name, domain_name = i.split('@')
        
        # 1st rule is if there is the . then remove it
        # 2nd rule if + is present then remove whole part after + in local name 
        
        local_name = local_name.split('+')[0].replace('.','')
        unique_email.add(local_name+ '@'+ domain_name)
    return len(unique_email)
email= ["test+127.@gmail.com","hsdfs.d+nsns@gamil","jhdsfgsd.sd12@gmail.com"]
count = numuniqueemail(email)
print("Number of unique Emails addresses ",count)
        

Number of unique Emails addresses  3


In [5]:
def giveemail():
    
    email = input("Enter the email ")
    local_name, domain_name = email.split('@')
    local_name = local_name.split('+')[0].replace('.','')
    email = local_name +'@'+domain_name
    return email
df = giveemail()
print()
print("The correct email is ",df)



Enter the email trtx.jh+hhf@gmail.com

The correct email is  trtxjh@gmail.com


### FINDING OF POWER OF ELEMENT


In [2]:
def DAC_power(a,n):
    # small problem
    if n == 1:
        return a
    # for big problem 
    # we are using divide and conquer stategy
    
    else:
        mid = n//2
        b = DAC_power(a,mid)
        c = b*b
    
    # but if there is odd and even number 
        if n % 2==0:
            return c
        else :
            return c*a
a = int(input("enter the number "))
n = int(input("enter the power value "))
value = DAC_power(a,n)
print()
print("The ans is ",value)


enter the number 2
enter the power value 64

The ans is  18446744073709551616


### MERGE SORT

In [4]:
def mergesort(array):
    if len(array) > 1:
        mid = len(array)//2
        # only value which are present before middle value
        # middle value is not taken
        left_side = array[:mid]
        
        # all value after middle value include middle value too
        right_side = array[mid:]
        # sorting left subtree
        mergesort(left_side)
        # sorting right sub tree
        mergesort(right_side)
        
        i = j= k = 0
        while i < len(left_side) and j < len(right_side):
            if left_side[i] < right_side[j]: # comparison 
                array[k] = left_side[i] # value present at i index is small so it is put in new array
                i += 1
            else:
                # value of j is small then put it in new array
                array[k] = right_side[j]
                j+=1
            k+= 1 # while loop incriment
        # checking if any element was left
        while i < len(left_side):
            array[k] = left_side[i]
            i += 1
            k += 1
        while j < len(right_side):
            array[k] = right_side[j]
            j += 1
            k+=1
def printlist(array):
    for i in range(len(array)):
        print(array[i], end = " ")
    print()
if __name__ == '__main__':
    array =[]
    n = int(input("Enter the lenght of array "))
    for i in range(0,n):
        x = int(input())
        array.append(x)
    print("The give array is ")
    print(array)
    print()
    mergesort(array)
    print("Sorted array is ")
    printlist(array)
                

Enter the lenght of array 5
9
98
56
2
78
The give array is 
[9, 98, 56, 2, 78]

Sorted array is 
2 9 56 78 98 


### max and min in an Array

In [3]:
# THIS IS BRUTE FORCE APPROACH 
# TIME COMPLEXITY = O(n)

def maxmin(array):
    max1 = array[0]
    min1 = array[0]
    n = len(array)
    for i in range(1,n-1):
        if array[i]> max1:
             max1 = array[i]
        else :
            if array[i] < min1:
                min1 = array[i]
            
    return max1,min1
array = [123,56,1,34,67]
maxmin(array)
                                

(123, 1)

In [1]:
import datetime

In [5]:
x = datetime.datetime.now().date()

In [6]:
x

datetime.date(2022, 8, 17)

In [4]:
n=5
for i in range(1,n-1):
    print(i)

1
2
3


In [1]:
def DAC_maxmin(array,low,high):
    max_value = array[0]
    min_value = array[0]
    # small problem                                # TC=O(1)
    if low== high:
        return (max_value,min_value)
    # for 2 elment
    elif low == high-1:                            # TC=O(1)
        if array[low]> array[high]:
            max_value = array[low]
            min_value = array[high]
        else:
            max_value = array[high]
            min_value = array[low]
        return (max_value,min_value)
    else:
        mid = low + (high-low)//2
        max_1,min_1 = DAC_maxmin(array,low,mid)     # TC = O(n/2)            ----\
        max_2,min_2 =DAC_maxmin(array,mid+1,high)   # TC = O(n/2)            ----\ -------> TC = O(n)
    return (max(max_1,max_2),min(min_1,min_2))
array =[23,7,89,4,788,3]
high = len(array) -1
low =0
max_value,min_value =DAC_maxmin(array,low,high)
print("The minimum value in array is ",min_value)
print("The maximum value in array is ",max_value)
            
            

The minimum value in array is  4
The maximum value in array is  788


In [2]:
def inserted_index(array,target):
    for i in range(len(array)):
        if array[i] == target:
            return i
        elif array[i]> target:
            return i
            
                          # array is sorted 
 
    return len(array)
array =[1,2,4,6]
target = 7

print("the index is ",inserted_index(array,target))

the index is  4


### FINDING OF NUMBER OF INVERSION

### QUICK SORT 

In [3]:
def partition(array,low,high):
    pivot = array[low]
    i = low
    for j in range(low+1,high+1):
        if array[j]<=pivot:
            i +=1
            array[i],array[j] = array[j],array[i]
        
    array[i],array[low] = array[low],array[i]
    return i
def quicksort(array,low,high):
    if len(array)==1:
        return array
    if low<high:
        m = partition(array,low,high)
        quicksort(array,low,m-1)
        quicksort(array,m+1,high)
array = [12,56,3,88,45,4,90]
quicksort(array,0,6)
print(array)

[3, 4, 12, 45, 56, 88, 90]
